### ISSUE TITLE
Can't copy generated password in Android Chrome.

### ISSUE THREAD

**Issue by matofesi** [eterevsky/passwordgen#8]
This time I have a problem with on-line generator - the "Copy" function doesn't really work for me. I use Linux and Android and Chrome browser on both of them.
On Linux clicking "Copy" selects generated password but it doeasn't actually copy it to clipboard - as I have my system configured with X selection disabled (as foar as it's possible) I have to press CTRL+C to do actual copying. This is not a big problem thanks to Chrome extension - bigger problem is on Android. There clicking Copy doesn't do anything (I use the latest stable Chrome on Samsung Galaxy S4 with Android 4.4.2 installed) and - as the password field is marked as read only I can't even select the password to copy it manually so the generator is almost useless as I need to retype generated password switching between pages/apps.

**Comment by eterevsky** [comment]
So, first of all, it seems that there is no good way to copy something to a clipboard in a web page. The only workaround uses Flash, that is not available in some mobile browsers. Hence, I renamed "Copy" button to "Select" to avoid confusion.

Also there's an [ugly Chromium bug](https://code.google.com/p/chromium/issues/detail?id=152552) that prevents selection of a readonly input. To work around it I made the password field non-readonly and removed the "Select" button altogether since it seems to be useless.

P.S. I really have to write a native Android client.
